### ISSUE TITLE
text input using system keyboard works except for '.'

### ISSUE THREAD

**Issue by hansent** [kivy/kivy-berkelium#3]
on text filed in berkelium browser widget all text inout seem to work excetp '.'  
I've checked  on_window_keyboard function inWebbrowser class of  extensions **init**.py file.  value of key = 44, both key event and text event are called but does not enter it in teh text field.  

makes it impossible to enter email address

**Comment by akshayaurora** [comment]
arrow keys don't seem to work either.

**Comment by schoolsplay** [comment]
Any chance that this issue can be fixed or is berkelium extension dead ?

**Comment by schoolsplay** [comment]
Ok, no replies or reactions to this bug so I had to dive in myself as we, at formatics.nl, want
to use it in one of our major projects.

I can't seems to attach a patch but I've fix this problem.
I've posted the patch to the kivy mailinglist:
https://groups.google.com/forum/?fromgroups=#!searchin/kivy-users/berkelium/kivy-users/VbWzxZJL7wQ/SpR3ZclmxUYJ

Greetings,
Stas Zytkiewicz
